substitutions:
  devicename: atomlite-distance

esphome:
  name: $devicename
  name_add_mac_suffix: true
  platformio_options:
    build_flags:
      - -D CORE_DEBUG_LEVEL=0
      - -D ARDUINO_LOG_LEVEL=0

esp32:
  board: m5stack-atom


uart:
  id: uart_sensor
  tx_pin: GPIO26
  rx_pin: GPIO32
  baud_rate: 9600


sensor:
  - platform: a02yyuw
    uart_id: uart_sensor
    name: distance
    id: distance

wifi:
  manual_ip:
    static_ip: 192.168.40.21
    gateway: 192.168.40.1
    subnet: 255.255.255.0
  reboot_timeout: 15min
  output_power: 15dB
  power_save_mode: none
  ap:

captive_portal:

improv_serial:

logger:
  level: DEBUG
  logs:
    sensor: WARN
    text_sensor: WARN

api:
  reboot_timeout: 0s

ota:
  - platform: esphome

web_server:
  include_internal: false
  version: 3


safe_mode:
  disabled: true

